apiVersion: v1
kind: ConfigMap
metadata:
  name: helep-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: helep
    component: config
data:
  KAFKA_BOOTSTRAP: {{ .Values.global.kafka.bootstrap | quote }}
  MATCHER: "simple"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: {{ .Release.Namespace }}
data:
  DB_PATH: "/data/user.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sos-service-config
  namespace: {{ .Release.Namespace }}
data:
  DB_PATH: "/data/sos.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch-service-config
  namespace: {{ .Release.Namespace }}
data:
  DB_PATH: "/data/dispatch.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: {{ .Release.Namespace }}
data:
  DB_PATH: "/data/notification.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: {{ .Release.Namespace }}
data:
  DB_PATH: "/data/analytics.db"
