apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helep-user-service
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
    - helep
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helep-sos-service
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: sos-service
  namespaceSelector:
    matchNames:
    - helep
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helep-dispatch-service
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: dispatch-service
  namespaceSelector:
    matchNames:
    - helep
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helep-notification-service
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: notification-service
  namespaceSelector:
    matchNames:
    - helep
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helep-analytics-service
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: analytics-service
  namespaceSelector:
    matchNames:
    - helep
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
